version: '3'
services:
    db:
        hostname: db
        image: mysql:5
        command: --default-authentication-plugin=mysql_native_password
        restart: always
#        volumes:
#            - ../data/mysql/data:/var/lib/mysql
#            - ../data/mysql/conf:/etc/mysql/conf.d
#            - ../data/mysql/initdb:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: starter
            MYSQL_ROOT_PASSWORD: root

    cache:
        hostname: cache
        image: redis:4
        command: redis-server --appendonly yes
        restart: always
#        volumes:
#            - ../data/redis:/data
        ports:
            - 6379:6379

    mq:
        hostname: mq
        image: webcenter/activemq:latest
        restart: always
        ports:
            - 61616:61616
            - 8161:8161

    elasticsearch:
        hostname: elasticsearch
        image: elasticsearch:latest
        restart: always
        ports:
            - 9200:9200
            - 9300:9300

    log:
        hostname: log
        image: registry.cn-shanghai.aliyuncs.com/hellodock/logstash:latest
        restart: always
        ports:
            - 9600:9600
            - 9601:9601
        depends_on:
            - elasticsearch

    kibana:
        image: registry.cn-shanghai.aliyuncs.com/hellodock/kibana:latest
        restart: always
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch

    db_admin:
        image: adminer:latest
        restart: always
        ports:
            - 3006:8080
        depends_on:
            - db

    api:
        image: registry.cn-shanghai.aliyuncs.com/jext/starter_api:latest
        restart: always
#        volumes:
#            - ../data/file:/tmp/file
        ports:
            - 8011:8011
        depends_on:
            - db
            - cache
            - mq
            - log

    admin:
        image: starter_admin:latest
        build:
          context: .
          dockerfile: Dockerfile_ce
        restart: always
        ports:
            - 8010:8010
        depends_on:
           - api
